# Generated by Django 5.1 on 2024-08-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="description", new_name="customer_PO",
        ),
    ]
