# Generated by Django 5.1 on 2024-08-20 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_description_order_customer_po"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="buyer", field=models.TextField(default="Unknown"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(verbose_name=datetime.date(2024, 8, 20)),
        ),
    ]
