# Generated by Django 5.1 on 2024-08-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_buyer_alter_order_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="buyer", field=models.TextField(),
        ),
    ]
