# Generated by Django 5.1 on 2024-08-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_buyer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="customer_PO", new_name="customer_po",
        ),
    ]
