# Generated by Django 5.1 on 2024-08-21 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_rename_customer_po_order_customer_po"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(verbose_name=datetime.date(2024, 8, 21)),
        ),
    ]
