# Generated by Django 5.1 on 2024-08-27 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(verbose_name=datetime.date(2024, 8, 27)),
        ),
    ]
