# Generated by Django 4.2.16 on 2024-10-01 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_alter_order_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(verbose_name=datetime.date(2024, 10, 1)),
        ),
    ]
