# Generated by Django 5.1 on 2024-08-16 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_rename_description_order_customer_po"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.CharField(max_length=10)),
                ("part_number", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField()),
                ("ship_via", models.CharField(max_length=5)),
                ("required_date", models.DateField()),
                ("updated_confirm_date", models.DateField()),
                ("original_confirm_date", models.DateField()),
                ("factory", models.TextField()),
                ("balance", models.IntegerField()),
                ("status", models.CharField(max_length=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
    ]
