# Generated by Django 5.1 on 2024-08-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_lines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="balance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="original_confirm_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="updated_confirm_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
