# Generated by Django 5.1 on 2024-08-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_lines", "0002_alter_orderline_balance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderline", old_name="order", new_name="order_id",
        ),
    ]
