# Generated by Django 5.1 on 2024-08-16 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_lines", "0004_rename_order_id_orderline_order"),
        ("orders", "0002_rename_description_order_customer_po"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="orders.order",
            ),
        ),
    ]
