# Generated by Django 5.1 on 2024-08-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_lines", "0005_alter_orderline_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderline",
            old_name="original_confirm_date",
            new_name="confirmed_date",
        ),
        migrations.RemoveField(model_name="orderline", name="updated_confirm_date",),
        migrations.AddField(
            model_name="orderline",
            name="print_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="revision",
            field=models.TextField(blank=True, null=True),
        ),
    ]
