# Generated by Django 5.1 on 2024-08-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "order_lines",
            "0006_rename_original_confirm_date_orderline_confirmed_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="orderline", name="print_number",),
        migrations.RemoveField(model_name="orderline", name="revision",),
    ]
