# Generated by Django 5.1 on 2024-08-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_lines", "0007_remove_orderline_print_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="factory",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
