# Generated by Django 5.1 on 2024-08-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_lines", "0008_alter_orderline_factory_alter_orderline_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="dwg_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="material",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="revision",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
