# Generated by Django 5.1 on 2024-08-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_lines", "0009_orderline_dwg_number_orderline_material_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="dwg_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="material",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="revision",
            field=models.TextField(blank=True, null=True),
        ),
    ]
