# Generated by Django 5.1 on 2024-08-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "order_lines",
            "0010_alter_orderline_dwg_number_alter_orderline_material_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="weight",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
