# Generated by Django 5.1 on 2024-08-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_lines", "0011_alter_orderline_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
