# Generated by Django 5.1 on 2024-09-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_lines", "0013_orderline_pay_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="unit",
            field=models.TextField(blank=True, null=True),
        ),
    ]
