# Generated by Django 5.1 on 2024-08-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("sold_to_address_line1", models.TextField(blank=True, null=True)),
                ("sold_to_address_line2", models.TextField(blank=True, null=True)),
                ("sold_to_address_line3", models.TextField(blank=True, null=True)),
                ("sold_to_address_line4", models.TextField(blank=True, null=True)),
                ("sold_to_contact_person", models.TextField(blank=True, null=True)),
                ("sold_to_phone", models.TextField(blank=True, null=True)),
                ("sold_to_email", models.TextField(blank=True, null=True)),
                ("ship_to_address_line1", models.TextField(blank=True, null=True)),
                ("ship_to_address_line2", models.TextField(blank=True, null=True)),
                ("ship_to_address_line3", models.TextField(blank=True, null=True)),
                ("ship_to_address_line4", models.TextField(blank=True, null=True)),
                ("ship_to_contact_person", models.TextField(blank=True, null=True)),
                ("ship_to_phone", models.TextField(blank=True, null=True)),
                ("ship_to_email", models.TextField(blank=True, null=True)),
                ("dispatch_address_line1", models.TextField(blank=True, null=True)),
                ("dispatch_address_line2", models.TextField(blank=True, null=True)),
                ("dispatch_address_line3", models.TextField(blank=True, null=True)),
                ("dispatch_address_line4", models.TextField(blank=True, null=True)),
                ("dispatch_contact_person", models.TextField(blank=True, null=True)),
                ("dispatch_phone", models.TextField(blank=True, null=True)),
                ("dispatch_email", models.TextField(blank=True, null=True)),
                ("plant_id", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
