# Generated by Django 5.1 on 2024-08-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Company", new_name="Customer",),
    ]
