# Generated by Django 4.2.16 on 2024-10-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.TextField(blank=True, null=True)),
                ("dwg_number", models.TextField(blank=True, null=True)),
                ("revision", models.CharField(blank=True, max_length=10, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("material", models.TextField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("factory", models.TextField(blank=True, null=True)),
                ("min_inventory", models.IntegerField(blank=True, null=True)),
                ("max_inventory", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
