# Generated by Django 4.2.16 on 2024-10-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0003_rename_timestamp_inventoryrecord_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryrecord",
            name="time",
            field=models.DateField(auto_now_add=True),
        ),
    ]
