# Generated by Django 4.2.16 on 2024-10-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0004_alter_inventoryrecord_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryrecord",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
