# Generated by Django 4.2.16 on 2024-10-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0005_inventoryrecord_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryrecord", name="time", field=models.DateField(),
        ),
    ]
