# Generated by Django 5.1 on 2024-08-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=10)),
                ("part_number", models.TextField()),
                ("dwg_number", models.TextField()),
                ("revision", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.FloatField()),
                ("cost", models.FloatField()),
                ("material", models.TextField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("order_quantity", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
