# Generated by Django 5.1 on 2024-08-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="revision",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
