# Generated by Django 5.1 on 2024-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0003_alter_part_cost_alter_part_dwg_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="part_number",
            field=models.TextField(blank=True, null=True),
        ),
    ]
