# Generated by Django 5.1 on 2024-08-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0004_alter_part_part_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="factory",
            field=models.TextField(blank=True, null=True),
        ),
    ]
