# Generated by Django 5.1 on 2024-09-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0005_part_factory"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["customer_id", "part_number"],
                name="idx_customer_id_part_number",
            ),
        ),
    ]
