# Generated by Django 5.1 on 2024-08-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("address_line1", models.TextField(blank=True, null=True)),
                ("address_line2", models.TextField(blank=True, null=True)),
                ("address_line3", models.TextField(blank=True, null=True)),
                ("address_line4", models.TextField(blank=True, null=True)),
                ("contact_person", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("zip", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
