replicaCount: 1

image:
  repository: 692859903719.dkr.ecr.us-east-2.amazonaws.com/ecr-repo/django-app
  pullPolicy: IfNotPresent
  tag: "latest"  # You can set this to your build image tag dynamically

service:
  type: LoadBalancer
  port: 80

resources: {}
# Limits and requests for CPU and memory
# Example:
# resources:
#   limits:
#     cpu: 100m
#     memory: 256Mi
#   requests:
#     cpu: 100m
#     memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50